default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>

development:
  <<: *default
  database: kreatix_studio_development

test:
  <<: *default
  database: kreatix_studio_test

production:
  <<: *default
  database: kreatix_studio_production
